### ISSUE TITLE
Некорректная работа пульта РПДК в РИ-М

### ISSUE THREAD

**Issue by well3n41k** [andrey-yantsen/wb-mqtt-astra#6]
Добрый день! А подключали ли вы к РИМ пульт РПДК? Вот такой:
https://support.wirenboard.com/uploads/default/original/2X/c/cc6b08859e410d52e81a95ccad0226e7e6203f0c.jpeg
 После подключения устройство имеет такой вид:
https://support.wirenboard.com/uploads/default/original/2X/9/97a3b826b2eb55d31107fc02a42eb672cfaeef0c.png
 После я нажимал все три кнопки сверху вниз, и вот что появлялось:
https://support.wirenboard.com/uploads/default/original/2X/3/3c4e157ad85e392b266ce586e5c24d06a0b68367.png
https://support.wirenboard.com/uploads/default/original/2X/a/ab5eb9187c5fcb467262b9e96067b70e7cbb74f3.png
https://support.wirenboard.com/uploads/default/original/2X/e/e48481b8ed779f224e5db545f74b7b484ed09247.png
Но теперь нажимай не нажимай на кнопки, никакие чекбоксы не изменяются, ничего не происходит, только в RSSI цифры меняются, как быть то?
https://gist.github.com/well3n41k/7066e420eba151a5bcf7ab1dd0676143

**Comment by worried-networking** [comment]
На самом деле [вывод mosquito_sub](https://support.wirenboard.com/uploads/default/original/2X/2/21e9c83cf733fe167d676ba3fe61425c54fcf66b.png), который вы прислали, не показывает, что всё ок :) Попробуйте сделать бОльшую паузу — в какой-то момент должно прийти сообщение, заканчивающееся на `/Arm 0`. Если достаточно долго не нажимать кнопку постановки на охрану.

Про верхнюю кнопку — это кнопка тревоги, и с ней нужно чуть больше экспериментов — например попробуйте её подержать пару секунд и последить за сообщениями в mosquito_sub про Channel1. Проблема в том, что события от датчиков бывают 4 типов: "норма", "нарушение", "норма не подтверждённая", "нарушение не подтверждённое", и вот для кнопки тревоги, почему-то, приходят только сообщение "норма" и "норма не подтверждённая". Если не получится добиться нарушения, то нужно будет искать обходные пути.

**Comment by well3n41k** [comment]
Ну вот, "снял с охраны", написало что disarm 1, жду уже больше 5 минут, arm 0 не происходит.. сколько то ждать надо?) мне кажется что как то не работает.. я и по пол часа кнопки не трогал, в веб интерфейсе WB как были оба чекбокса включены так и оставались, arm и disarm

**Comment by well3n41k** [comment]
Красную держал подольше, вывод не меняется
/devices/astra_1_sensor_2/controls/Channel1 0
/devices/astra_1_sensor_2/controls/Arm_confirmed 0
/devices/astra_1_sensor_2/controls/Disarm_confirmed 0
/devices/astra_1_sensor_2/controls/Channel1 0
/devices/astra_1_sensor_2/controls/Arm_confirmed 0
/devices/astra_1_sensor_2/controls/Disarm_confirmed 0

**Comment by worried-networking** [comment]
Автоматически Arm=0 не придёт — только при нажатии другой кнопки. Сам РИ-М (как и мой драйвер) не следит за состоянием кнопок — этим занимается пульт.

**Comment by well3n41k** [comment]
Ок, понял. Ну опять же, нажал поставить = arm 1, нажал снять = disarm 1, 10 минут, arm 0 не возвращается..
Что я делаю не так?

**Comment by worried-networking** [comment]
Уточните порядок действий, пожалуйста. Нажали arm, подождали 10 минут, нажали disarm, так?

-- 
Andrey Yantsen
Badoo.com developer
Tel.: ‭‭+44 7564 966022‬‬
Skype: andrey_janzen

**Comment by worried-networking** [comment]
Я сейчас, к сожалению, живу вдали от wirenboard и РИ-М, и самостоятельно расследовать проблему не смогу. Только с вашей помощью.

А как вы хотите пульт использовать, если не секрет?

-- 
Andrey Yantsen
Badoo.com developer
Tel.: ‭‭+44 7564 966022‬‬
Skype: andrey_janzen

**Comment by well3n41k** [comment]
Да, именно так, нажал-подождал-нажал-подождал.. отлипания предыдущей кнопки не происходит :(
Помощь это без проблем..Ну так как и есть, постановка, снятие с охраны, тревожная кнопка, та же логика что и у теко с их астрой. Есть необходимость помещения котельных охранять, множество удаленных. Там где WB, хотелось бы его базу использовать для этого. Со сценарием работы с нашими программистами разберемся.
Вот я сейчас с сервера по VPN в WB запросы стрельнул, да и локально, так оно и выходит
```
root@bpium:~# mosquitto_sub -h 10.9.8.14 -t '/devices/astra_1_sensor_2/controls/Arm'
1
^C
root@bpium:~# mosquitto_sub -h 10.9.8.14 -t '/devices/astra_1_sensor_2/controls/Disarm'
1
^C
root@bpium:~# mosquitto_sub -h 10.9.8.14 -t '/devices/astra_1_sensor_2/controls/Arm_confirmed'
0
^C
root@bpium:~# mosquitto_sub -h 10.9.8.14 -t '/devices/astra_1_sensor_2/controls/Disarm_confirmed'
0
^C
```

**Comment by worried-networking** [comment]
В таком случае мне нужны отладочные логи, опыт у вас уже есть. Нужен чистый файл, после запуска демона действовать по такой схеме:

1. Подождать 10 секунд
2. Arm
3. Подождать 3 минуты
4. Disarm
5. Подождать 3 минуты
6. Тревога
7. Подождать 10 секунд и завершить процесс

Время пауз указано примерное, конечно же, с секундомером замерять не нужно.

-- 
Andrey Yantsen
Badoo.com developer
Tel.: ‭‭+44 7564 966022‬‬
Skype: andrey_janzen

**Comment by well3n41k** [comment]
https://gist.github.com/well3n41k/9f18c28d2636a60c06fd05853a1b5417

**Comment by well3n41k** [comment]
Вот, на гисте

**Comment by worried-networking** [comment]
Отлично, спасибо. В чём проблема с arm/disarm понял, постараюсь поправить сегодня.

**Comment by well3n41k** [comment]
Ох замечательно это... спасибо :)

**Comment by worried-networking** [comment]
Попробуйте, пожалуйста, сборку по ссылке: [wb-mqtt-astra.gz](https://github.com/andrey-yantsen/wb-mqtt-astra/files/2958043/wb-mqtt-astra.gz). Файл нужно распаковать (gunzip "имя файла"), положить в `/usr/bin/wb-mqtt-astra` (предварительно сделав бэкап существующего файла), и затем сделать его исполняемым (`chmod 755 /usr/bin/wb-mqtt-astra`). Если повезёт — всё волшебным образом заработает и ничего не отломается в неожиданных местах :)

**Comment by well3n41k** [comment]
Не заводится сервис с новым файлом..вот в логе:
SIGILL: illegal instruction
PC=0xd6664 m=0 sigcode=1

goroutine 1 [running, locked to thread]:
github.com/andrey-yantsen/teko-astra-go.init()
	/Users/virus/Development/Personal/teko-astra-go/device.go:74 +0x130 fp=0x1214bfb8 sp=0x1214bf8c pc=0xd6664
main.init()
	<autogenerated>:1 +0x4c fp=0x1214bfbc sp=0x1214bfb8 pc=0x1f4890
runtime.main()
	/usr/local/go/src/runtime/proc.go:186 +0x1b8 fp=0x1214bfe4 sp=0x1214bfbc pc=0x3d914
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:1015 +0x4 fp=0x1214bfe4 sp=0x1214bfe4 pc=0x6c344

trap    0x6
error   0x0
oldmask 0x0
r0      0x1214e1a0
r1      0x1214e1a0
r2      0x7586cf26
r3      0x6e0da69e
r4      0x75b1d9d5
r5      0x1c
r6      0xd4
r7      0x20
r8      0x8
r9      0x0
r10     0x121000e0
fp      0x390160
ip      0x0
sp      0x1214bf8c
lr      0x6d144
pc      0xd6664
cpsr    0x60000010
fault   0x0

**Comment by worried-networking** [comment]
У вас wb5?

-- 
Andrey Yantsen
Badoo.com developer
Tel.: ‭‭+44 7564 966022‬‬
Skype: andrey_janzen

**Comment by well3n41k** [comment]
@andrey-yantsen Да, 5.8

**Comment by worried-networking** [comment]
Ок, попробуйте этот файл, у меня запускается: [wb-mqtt-astra.gz](https://github.com/andrey-yantsen/wb-mqtt-astra/files/2960521/wb-mqtt-astra.gz).

**Comment by well3n41k** [comment]
Да, сейчас arm и disarm работают как надо, сервис кей сбрасывает нажатый arm или disarm

**Comment by worried-networking** [comment]
На самом деле это не "сервисная кнопка", а кнопка тревоги :) Я перепутал с другим пультом. В общем на текущий момент это всё, что я могу по-быстрому сделать. Возможно когда-нибудь в будущем будет решение и для кнопки тревоги.
Нажатие arm через некоторое время после disarm должно тоже сбрасывать disarm, и наоборот.

**Comment by well3n41k** [comment]
@andrey-yantsen Да, почти сразу, меньше секунды задержка в веб интерфейсе, а в mqtt сразу происходит. Спасибо большое за поддержку! Смотрю в светлое будущее и жду ту кнопку))
